[WIP]membersテーブルの設計仕様記述
naka5419/chat-space pull request #1
Opened 2019-01-05 07:08 UTC by naka5419

# WHAT
 マークダウン記法でデータベースの設計仕様を記述

# WHY
 データベース設計に必要なため

2019-01-06 07:14 UTC, ghost requested changes

2019-01-06 07:14 UTC, hiroki5123 commented on README.md
> +
アソシエーション書いてください

2019-01-06 07:14 UTC, hiroki5123 commented on README.md
> +
アソシエーションが2つ足りません

2019-01-06 07:14 UTC, hiroki5123 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
このカラムはどのような意図で作りましたか？

2019-01-06 07:14 UTC, hiroki5123 commented on README.md
> +|g_name|string|null: false|
nameでいいと思います

2019-01-06 07:14 UTC, hiroki5123 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
このカラムはどのような意図で作りましたか？

2019-01-06 07:14 UTC, hiroki5123 commented on README.md
> +
アソシエーションが2つ足りません

2019-01-06 08:59 UTC, naka5419 commented on README.md
> +
### Association
- belongs_to :group
- belongs_to :user

2019-01-06 09:00 UTC, naka5419 commented on README.md
> +
下記を追加
- has_many :messages
- has_many :groups

2019-01-06 09:00 UTC, naka5419 commented on README.md
> +|g_name|string|null: false|
g_name を name　に変えます。

2019-01-06 09:01 UTC, naka5419 commented on README.md
> +
下記を追加します
- has_many :messages
- has_many :users

2019-01-06 09:05 UTC, naka5419 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
申し訳有りません。users テーブルにgroup_idは必要ないと思います。

2019-01-06 09:36 UTC, hiroki5123 commented
修正部分が確認できません。
変更差分をpushしてください。

2019-01-08 11:30 UTC, hiroki5123 commented on README.md
> +- accepts_nested_attributes_for :members
has_many :users, through: :membersに直してください

2019-01-08 11:47 UTC, hiroki5123 commented
LGTMです！

2019-01-08 11:55 UTC, merged